name: Deploy on production merge
'on':
  push:
    branches:
      - production

jobs:
  deploy-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source directory
        uses: actions/checkout@v4
        with:
          path: source

      - name: Create build directory
        run: |
          mkdir build
          cp source/firebase.json build/firebase.json

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: 'source/pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install
        working-directory: source

      - name: Build client
        run: |
          pnpm --filter=better-uoa-cal-client build
          pnpm --filter=better-uoa-cal-client deploy --prod ../build/client
        working-directory: source
        env:
          VITE_REQUIRED_USERNAME: ${{ vars.REQUIRED_USERNAME }}
          VITE_TRPC_ENDPOINT: ${{ vars.TRPC_ENDPOINT }}
          VITE_CALENDAR_ENDPOINT: ${{ vars.CALENDAR_ENDPOINT }}

      - name: Build server
        run: |
          pnpm --filter=better-uoa-cal-server build
          pnpm --filter=better-uoa-cal-server deploy --prod ../build/server
        working-directory: source

      - name: Authenticate with Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
          create_credentials_file: true
          export_environment_variables: true

      - name: Setup Firebase CLI
        run: pnpm install -g firebase-tools

      - name: Deploy client to Firebase Hosting
        run: firebase --project better-uoa-cal deploy --only hosting
        working-directory: build

      - name: Deploy server to Firebase Functions
        run: firebase --project better-uoa-cal deploy --only functions
        working-directory: build
